adding bucket policy for s3 logging
ministryofjustice/cloud-platform-environments pull request #15458
Opened 2023-08-10 14:44 UTC by carrb-moj

2023-08-10 14:55 UTC, jakemulley requested changes

2023-08-10 14:55 UTC, jakemulley commented on namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-manage-intelligence-preprod/resources/s3-ims-legacy.tf
> +            }
```suggestion
        "Condition": {
            "ArnLike": {
                "aws:SourceArn": 
 ["${module.manage_intelligence_extractor_bucket.bucket_arn}", "${module.manage_intelligence_transformer_bucket.bucket_arn}"]
            }
```

2023-08-10 14:58 UTC, carrb-moj reviewed
Thanks

2023-08-11 08:14 UTC, jakemulley approved these changes

2023-08-11 08:23 UTC, merged