LNP-272: 🔍  add opensearch module to prisoner content hub dev environment
ministryofjustice/cloud-platform-environments pull request #16616
Opened 2023-09-21 16:56 UTC by Eli-TW

This will enable us to test pointing Drupal at OpenSearch instead of ElasticSearch.

2023-09-21 18:15 UTC, jakemulley requested changes

2023-09-21 18:15 UTC, jakemulley commented on namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/opensearch.tf
> +  source = "github.com/ministryofjustice/cloud-platform-terraform-s3-bucket?ref=4.9.0"
```suggestion
  source = "github.com/ministryofjustice/cloud-platform-terraform-s3-bucket?ref=5.0.0"
```

2023-09-21 18:15 UTC, jakemulley commented on namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/opensearch.tf
> +  source = "github.com/ministryofjustice/cloud-platform-terraform-s3-bucket?ref=4.9.0"
You won't need the access keys for this one :)

2023-09-21 18:16 UTC, jakemulley commented on namespaces/live.cloud-platform.service.justice.gov.uk/prisoner-content-hub-development/resources/opensearch.tf
> +  environment_name       = var.environment
```suggestion
  environment_name       = var.environment-name
```

2023-09-25 09:25 UTC, poornima-krishnasamy approved these changes

2023-09-25 09:31 UTC, merged