changing db instance class from micro to small
ministryofjustice/cloud-platform-environments pull request #17062
Opened 2023-10-17 14:02 UTC by varunkumar139

2023-10-18 15:08 UTC, jackstockley89 approved these changes

2023-10-18 15:20 UTC, jackstockley89 submitted a review, later dismissed

2023-10-18 15:29 UTC, jakemulley requested changes
Please see the [user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/upgrade.html#upgrading-to-a-new-major-database-version) for upgrading a database to a new major version.

2023-10-19 13:32 UTC, jaskaransarkaria approved these changes

2023-10-19 13:51 UTC, jakemulley approved these changes

2023-10-19 13:52 UTC, merged