PIC-4134 create new IRSA with SNS and S3 permissions
ministryofjustice/cloud-platform-environments pull request #25775
Opened 2024-09-06 14:47 UTC by markreesmoj

This will be used by court-hearing-event-receiver and crime-portal-gateway
Future PRs will remove these S3 and SNS permissions from the court-case-service IRSA

2024-09-06 15:14 UTC, jaskaransarkaria approved these changes

2024-09-06 15:15 UTC, jaskaransarkaria requested changes
Error: Reference to undeclared module


  on service-pod.tf line 5, in module "service_pod":

   5:   service_account_name = module.irsa.service_account.name

2024-09-06 15:35 UTC, markreesmoj commented
> Error: Reference to undeclared module
> 
> on service-pod.tf line 5, in module "service_pod":
> 
> 5: service_account_name = module.irsa.service_account.name

Thanks, interesting.

Our plan is to have two service accounts with different permissions. Would we have to have two service pods in that case or is there a way to have a pod with both service accounts?

2024-09-06 19:43 UTC, jaskaransarkaria submitted a review, later dismissed

2024-09-10 08:06 UTC, jaskaransarkaria approved these changes

2024-09-10 14:34 UTC, merged