PIC-4207 : Queue creation for prod probation-in-court-cases-queue
ministryofjustice/cloud-platform-environments pull request #26589
Opened 2024-10-03 17:42 UTC by sameermoj

JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-4207

2024-10-03 20:42 UTC, markreesmoj requested changes
Please add to the IRSA and rename as per dev

2024-10-04 07:34 UTC, markreesmoj approved these changes

2024-10-04 07:34 UTC, markreesmoj commented on namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/court-cases-queue.tf
> +# resource "aws_sqs_queue_policy" "court-cases-queue-policy" {
Please remove this commented out section

2024-10-04 08:40 UTC, timckt approved these changes

2024-10-07 14:53 UTC, merged