PIC-4207 : Queue creation for pre-prod probation-in-court-cases-queue
ministryofjustice/cloud-platform-environments pull request #26588
Opened 2024-10-03 17:33 UTC by sameermoj

JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-4207

2024-10-03 20:41 UTC, markreesmoj requested changes
Please rename to match the queue in dev as per the PR comments
When adding this queue to the IRSA, you will have to remove something. For now, I suggest the only possible candidate is the [S3 bucket for gatling tests](https://github.com/ministryofjustice/cloud-platform-environments/blob/92d3513c4de49d5c6eec3887761b6de973156434/namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/irsa.tf#L61)

2024-10-04 07:33 UTC, markreesmoj commented on namespaces/live.cloud-platform.service.justice.gov.uk/court-probation-preprod/resources/court-cases-queue.tf
> +# resource "aws_sqs_queue_policy" "court-cases-queue-policy" {
Please remove this commented out section

2024-10-04 07:33 UTC, markreesmoj approved these changes
👍

2024-10-04 08:41 UTC, timckt approved these changes

2024-10-04 11:16 UTC, merged