Added pingdom file
ministryofjustice/cloud-platform-environments pull request #4028
Opened 2021-01-11 15:56 UTC by katie-cawthorne

2021-01-11 16:03 UTC, mogaal submitted a review, later dismissed

2021-01-12 05:45 UTC, digitalronin requested changes

2021-01-12 05:45 UTC, digitalronin commented on namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/pingdom.tf
> +  host                     = "/https/${var.prepare-case-domain}"
I haven't seen this syntax used for `host` before. 

If you check the other `pingdom.tf` files in the namespaces folder, they seem to just put the domain, without specifying any protocol, e.g.

```
$ ls -1 */resources/pingdom.tf | xargs grep host
...
cccd-production/resources/pingdom.tf:  host                     = "claim-crown-court-defence.service.gov.uk"
cccd-staging/resources/pingdom.tf:  host                     = "staging.claim-crown-court-defence.service.justice.gov.uk"
check-my-diary-prod/resources/pingdom.tf:  host                     = "checkmydiary.service.justice.gov.uk"
...
```
That agrees with the documentation for the pingdom provider, here:
https://github.com/russellcardullo/terraform-provider-pingdom#pingdom-check

2021-01-12 05:45 UTC, digitalronin commented on namespaces/live-1.cloud-platform.service.justice.gov.uk/court-probation-prod/resources/pingdom.tf
> +  integrationids           = []
I've set up the pingdom/slack integration. The integration ID is 110432, so please add that here when you make the change above.

2021-01-12 08:05 UTC, digitalronin approved these changes

2021-01-12 08:19 UTC, merged