Add push gateway
ministryofjustice/cloud-platform-environments pull request #4341
Opened 2021-02-18 15:53 UTC by BarryPiccinni

The team have a need to push the output of ephemeral jobs to Prometheus.

This PR adds the pushgateway to the DEV environment to facilitate this.

2021-02-18 15:58 UTC, mogaal submitted a review, later dismissed

2021-02-24 19:22 UTC, jasonBirchall requested changes
Hi Barry, there are a couple of tweaks that are completely our fault. Everything else looks good.

2021-02-24 19:22 UTC, jasonBirchall commented on namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/versions.tf
> +  required_version = "0.12.17"
I would leave the required version at ">=0.12" for now. The pipeline uses 0.12.30 and we're in the process of a migration (be it a little slow).

2021-02-24 19:22 UTC, jasonBirchall commented on namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-dev/resources/pushgateway.tf
> +  source = "github.com/ministryofjustice/cloud-platform-terraform-pushgateway?ref=1.2"
Can you bump this down to 1.1. 1.2 contains the necessary code for 0.13. Really sorry for the confusion here.

2021-02-24 20:05 UTC, BarryPiccinni commented
@jasonBirchall Hi Jason, thanks for the review, that was really helpful. I was messing with the versions after I got an error in the build, but actioning the above has fixed it.

2021-02-25 09:33 UTC, jasonBirchall approved these changes

2021-02-25 11:55 UTC, merged