Add RDS for sandbox-ppse namespace
ministryofjustice/cloud-platform-environments pull request #4770
Opened 2021-05-13 16:11 UTC by mr-ken

2021-05-14 09:06 UTC, vijay-veeranki requested changes
Can you please use the latest module of RDS
github.com/ministryofjustice/cloud-platform-terraform-rds-instance?ref=5.16

2021-05-14 15:03 UTC, mr-ken commented
> Can you please use the latest module of RDS
> github.com/ministryofjustice/cloud-platform-terraform-rds-instance?ref=5.16

changed.

Do you know why the status check is failing?
```
executing: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/sandbox-ppse/resources; terraform plan  
Command: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/sandbox-ppse/resources; terraform plan   failed.

Error: Unsupported argument

  on rds.tf line 5, in module "rds":
   5:   cluster_state_bucket = var.cluster_state_bucket

An argument named "cluster_state_bucket" is not expected here.

Traceback (most recent call last):
	10: from ./bin/plan:20:in `<main>'
	 9: from ./bin/plan:9:in `main'
	 8: from ./bin/plan:15:in `plan_namespaces'
	 7: from ./bin/plan:15:in `each'
	 6: from ./bin/plan:16:in `block in plan_namespaces'
	 5: from /tmp/build/6818cc24/cloud-platform-environments-live-1-pull-requests/lib/cp_env/pipeline.rb:59:in `plan_namespace_dir'
	 4: from /tmp/build/6818cc24/cloud-platform-environments-live-1-pull-requests/lib/cp_env/pipeline.rb:70:in `plan_terraform'
	 3: from /tmp/build/6818cc24/cloud-platform-environments-live-1-pull-requests/lib/cp_env/terraform.rb:37:in `plan'
	 2: from /tmp/build/6818cc24/cloud-platform-environments-live-1-pull-requests/lib/cp_env/terraform.rb:79:in `tf_plan'
	 1: from /tmp/build/6818cc24/cloud-platform-environments-live-1-pull-requests/lib/cp_env/pipeline.rb:82:in `execute'
/tmp/build/6818cc24/cloud-platform-environments-live-1-pull-requests/lib/cp_env/executor.rb:11:in `execute': unhandled exception
```

2021-05-17 12:01 UTC, mr-ken commented
> Can you please use the latest module of RDS
> github.com/ministryofjustice/cloud-platform-terraform-rds-instance?ref=5.16

Hi Vijay - this change has been made. Can you approve?

2021-05-17 15:21 UTC, vijay-veeranki approved these changes

2021-05-17 15:24 UTC, merged