Add 'laa-view-court-data-prototype' namespace
ministryofjustice/cloud-platform-environments pull request #7448
Opened 2022-03-14 15:20 UTC by dfrmptn

Following the guidance here: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/prototype-kit.html#publish-prototypes-on-the-web

2022-03-14 15:26 UTC, razvan-moj commented on namespaces/live.cloud-platform.service.justice.gov.uk/laa-view-court-data-prototype/resources/variables.tf
> +variable "basic-auth-username" {
Hi - these are publicly visible, so not much use. You probably want a random string generated, via terraform's https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password

2022-03-14 15:26 UTC, razvan-moj requested changes
see comment about basic pass

2022-03-14 17:29 UTC, dfrmptn commented
I've checked with some other designers who have done the same with their prototypes. There weren't any issues with their PRs and they had the username and password visible:

https://github.com/ministryofjustice/cloud-platform-environments/blob/a88d726a909d4acfd2172bb494c06b60dac3bdab/namespaces/live.cloud-platform.service.justice.gov.uk/apply-for-compensation-prototype/resources/variables.tf#L61-L68

https://github.com/ministryofjustice/cloud-platform-environments/blob/a88d726a909d4acfd2172bb494c06b60dac3bdab/namespaces/live.cloud-platform.service.justice.gov.uk/opg-lpa-fd-prototype/resources/variables.tf#L61-L68

Because it's only a prototype for exploring solutions, the login was just meant to stop members of the public coming across prototypes by accident (https://design-patterns.service.justice.gov.uk/get-started/deploying-your-prototype/#deploying-to-heroku).

2022-03-15 10:53 UTC, razvan-moj approved these changes

2022-03-16 11:03 UTC, merged